import { createClient, type SupabaseClient } from "https://esm.sh/@supabase/supabase-js@2";
import { cleanSummary } from "./content-safety.ts";
import type { RunStatus } from "./agent-contracts.ts";

export interface AgentRun { id: string; user_id: string; run_type: string; course_id: string | null; status: RunStatus; idempotency_key: string; cancel_requested: boolean; input: Record<string, unknown>; output?: unknown; error?: string | null; lease_token?: string | null; lease_expires_at?: string | null; attempt_count?: number; }
export type ClaimedAgentRun = AgentRun & { lease_token: string; lease_expires_at: string };
export interface AgentStep { id: string; run_id: string; step_key: string; sequence: number; status: RunStatus; input?: Record<string, unknown>; output?: unknown; error?: string | null; attempt_count?: number; lease_token?: string | null; lease_expires_at?: string | null; }
export function serviceClient(): SupabaseClient { const url = Deno.env.get("SUPABASE_URL"); const key = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"); if (!url || !key) throw new Error("supabase_service_not_configured"); return createClient(url, key, { auth: { persistSession: false, autoRefreshToken: false } }); }
export async function requireUser(client: SupabaseClient, authorization: string | null): Promise<{ id: string }> { const token = authorization?.match(/^Bearer\s+(.+)$/i)?.[1]; if (!token) throw new Error("unauthorized"); const { data, error } = await client.auth.getUser(token); if (error || !data.user) throw new Error("unauthorized"); return { id: data.user.id }; }
export async function getOwnedRun(client: SupabaseClient, runId: string, userId: string): Promise<AgentRun> { const { data, error } = await client.from("agent_runs").select("id,user_id,run_type,course_id,status,idempotency_key,cancel_requested,input,lease_token,lease_expires_at,attempt_count").eq("id", runId).eq("user_id", userId).maybeSingle(); if (error || !data) throw new Error("run_not_found"); return data as AgentRun; }
export async function claimRun(client: SupabaseClient, runId: string, userId: string, expectedStatus: "queued" | "failed" | "running"): Promise<ClaimedAgentRun | null> { const { data, error } = await client.rpc("claim_agent_run", { p_run_id: runId, p_user_id: userId, p_expected_status: expectedStatus }); if (error) throw new Error(error.message === "invalid_expected_status" ? "run_claim_invalid" : "run_claim_failed"); if (!data) return null; const claimed = data as AgentRun; if (typeof claimed.lease_token !== "string" || typeof claimed.lease_expires_at !== "string") throw new Error("run_claim_invalid"); return claimed as ClaimedAgentRun; }
export async function setRunStatus(client: SupabaseClient, runId: string, userId: string, runLeaseToken: string, status: RunStatus, error?: unknown): Promise<void> { const { data, error: rpcError } = await client.rpc("set_agent_run_status", { p_run_id: runId, p_user_id: userId, p_status: status, p_lease_token: runLeaseToken, p_error: error ? cleanSummary(error, 500) : null }); if (rpcError) { if (rpcError.message === "run_not_found") throw new Error("run_not_found"); if (rpcError.message === "run_lease_lost") throw new Error("run_lease_lost"); throw new Error("run_update_failed"); } if (!data) throw new Error("run_update_conflict"); }
export async function requestCancellation(client: SupabaseClient, runId: string, userId: string): Promise<void> { const { data, error } = await client.rpc("request_agent_run_cancellation", { p_run_id: runId, p_user_id: userId }); if (error) throw new Error(error.message === "run_not_found" ? "run_not_found" : "run_cancel_failed"); if (!data) throw new Error("run_cancel_failed"); }
export async function assertRunLease(client: SupabaseClient, runId: string, runLeaseToken: string): Promise<void> { const { data, error } = await client.from("agent_runs").select("status,cancel_requested,lease_token,lease_expires_at").eq("id", runId).maybeSingle(); if (error || !data) throw new Error("run_lease_lost"); if (data.cancel_requested === true || data.status === "cancelled") throw new Error("run_cancelled"); if (data.status !== "running" || data.lease_token !== runLeaseToken || typeof data.lease_expires_at !== "string" || Date.parse(data.lease_expires_at) <= Date.now()) throw new Error("run_lease_lost"); }
export async function assertNotCancelled(client: SupabaseClient, runId: string): Promise<void> { const { data, error } = await client.from("agent_runs").select("status,cancel_requested").eq("id", runId).maybeSingle(); if (error || !data) throw new Error("run_not_found"); if (data.status === "cancelled" || data.cancel_requested === true) throw new Error("run_cancelled"); }
export async function claimStep(client: SupabaseClient, runId: string, runLeaseToken: string, key: string, sequence: number, input: unknown): Promise<AgentStep | null> { const { data, error } = await client.rpc("claim_agent_step", { p_run_id: runId, p_step_key: key, p_sequence: sequence, p_input: input ?? {}, p_run_lease_token: runLeaseToken, p_lease: "10 minutes" }); if (error) { if (error.message === "run_cancelled") throw new Error("run_cancelled"); if (error.message === "run_lease_lost") throw new Error("run_lease_lost"); if (error.message === "step_retry_limit_reached") throw new Error("step_retry_limit_reached"); if (error.message === "step_sequence_conflict") throw new Error("step_sequence_conflict"); throw new Error("step_claim_failed"); } return data ? data as AgentStep : null; }
async function resolveClaimMiss(client: SupabaseClient, runId: string, runLeaseToken: string, key: string): Promise<"completed"> { await assertRunLease(client, runId, runLeaseToken); const { data: step, error } = await client.from("agent_steps").select("status").eq("run_id", runId).eq("step_key", key).maybeSingle(); if (error) throw new Error("step_state_lookup_failed"); if (step?.status === "completed") return "completed"; if (step?.status === "cancelled") throw new Error("run_cancelled"); if (step?.status === "running" || step?.status === "queued") throw new Error("step_busy"); throw new Error("step_claim_unavailable"); }
export async function runStep<T>(client: SupabaseClient, runId: string, runLeaseToken: string, key: string, sequence: number, input: unknown, task: () => Promise<T>): Promise<T | undefined> { let step = await claimStep(client, runId, runLeaseToken, key, sequence, input); if (!step) { await resolveClaimMiss(client, runId, runLeaseToken, key); return undefined; } for (;;) { const started = Date.now(); let result: T; try { await assertRunLease(client, runId, runLeaseToken); result = await task(); await assertRunLease(client, runId, runLeaseToken); } catch (error) { const message = error instanceof Error ? error.message : String(error); const cancelled = message.includes("run_cancelled"); const leaseLost = message.includes("run_lease_lost") || message.includes("step_lease_lost"); if (cancelled) { try { await finishStep(client, step, runLeaseToken, "cancelled", undefined, Date.now() - started, error); } catch { /* cancellation RPC may have already fenced this step */ } throw new Error("run_cancelled"); } if (leaseLost) throw new Error("run_lease_lost"); try { await finishStep(client, step, runLeaseToken, "failed", undefined, Date.now() - started, error); } catch (finishError) { throw finishError; } step = await claimStep(client, runId, runLeaseToken, key, sequence, input); if (!step) { await resolveClaimMiss(client, runId, runLeaseToken, key); return undefined; } continue; } try { await finishStep(client, step, runLeaseToken, "completed", result, Date.now() - started); return result; } catch (error) { const message = error instanceof Error ? error.message : String(error); if (message.includes("run_lease_lost") || message.includes("step_lease_lost")) throw new Error(message.includes("run_lease_lost") ? "run_lease_lost" : "step_lease_lost"); throw new Error("step_update_failed"); } } }
async function finishStep(client: SupabaseClient, step: AgentStep, runLeaseToken: string, status: RunStatus, output?: unknown, durationMs?: number, error?: unknown): Promise<void> { const { data, error: rpcError } = await client.rpc("finish_agent_step", { p_step_id: step.id, p_lease_token: step.lease_token ?? null, p_run_lease_token: runLeaseToken, p_status: status, p_output: output ?? null, p_error: error ? cleanSummary(error, 500) : null, p_duration_ms: durationMs ?? 0 }); if (rpcError) { if (rpcError.message === "run_lease_lost") throw new Error("run_lease_lost"); throw new Error("step_update_failed"); } if (!data) throw new Error("step_lease_lost"); }
export async function completedOutput<T>(client: SupabaseClient, runId: string, key: string, validate: (value: unknown) => T): Promise<T> { const { data, error } = await client.from("agent_steps").select("output").eq("run_id", runId).eq("step_key", key).eq("status", "completed").maybeSingle(); const value = record(data?.output).value; if (error || value === undefined) throw new Error("completed_step_output_missing"); return validate(value); }
function record(value: unknown): Record<string, unknown> { return value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
